name: takweela
description: التشكيلة — تطبيق حجز مقاعد كرة القدم
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8

  # State management
  provider: ^6.1.2

  # Local storage
  shared_preferences: ^2.2.2

  # Image picking & compression
  image_picker: ^1.0.7
  flutter_image_compress: ^2.2.0

  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
